import { useEffect, useState } from 'react'
import { supabase } from '../supabase'

type Kind = 'gallery'|'videos'|'live'|'audio'
const input='admin-input'
const galleryDefaults = { image_fit: 'cover' }

export function AdminContentManager({kind}:{kind:Kind}) {
 const [items,setItems]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[saving,setSaving]=useState(false),[preview,setPreview]=useState('')
 const [form,setForm]=useState<any>({title:'',speaker:'',scripture:'',category:'Faith',video_url:'',thumbnail_url:'',is_featured:false,episode:'Ep. 1',duration:'',audio_url:'',image_url:'',stream_url:'',is_live:false,...galleryDefaults})
 const title=kind==='gallery'?'Gallery Moments':kind==='videos'?'Video Sermons':kind==='live'?'Live Broadcast':'Audio Messages',table=kind==='gallery'?'gallery_moments':kind==='videos'?'sermons':kind==='live'?'live_stream':'audio_sermons'
 const load=async()=>{const q=kind==='live'?supabase.from(table).select('*').eq('id',1).maybeSingle():supabase.from(table).select('*').order('created_at',{ascending:false});const {data,error}=await q;if(error){alert(error.message);return}setItems(kind==='live'?(data?[data]:[]):data||[])}
 useEffect(()=>{load()},[kind])
 const reset=()=>{setEditing(null);setPreview('');setForm({title:'',speaker:'',scripture:'',category:'Faith',video_url:'',thumbnail_url:'',is_featured:false,episode:'Ep. 1',duration:'',audio_url:'',image_url:'',stream_url:'',is_live:false,...galleryDefaults})}
 const edit=(x:any)=>{setEditing(x);setForm({...x,image_fit:x.image_fit==='contain'?'contain':'cover'});setPreview(x.image_url||x.thumbnail_url||'')}
 const update=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}))
 const upload=async(e:React.ChangeEvent<HTMLInputElement>,field:string,bucket:string)=>{const file=e.target.files?.[0];if(!file)return;const local=URL.createObjectURL(file);setPreview(local);const ext=file.name.split('.').pop()||'bin';const path=`admin/${Date.now()}_${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type});if(error){alert(error.message);return}const u=supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;update(field,u);setPreview(u)}
 const uploadAudio=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('audio/')){alert('Please select an audio file.');return}if(file.size>100*1024*1024){alert('Audio files must be 100 MB or smaller.');return}const local=URL.createObjectURL(file);setPreview(local);const ext=file.name.split('.').pop()||'mp3';const path=`audio/${Date.now()}_${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabase.storage.from('audio').upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type});if(error){alert(`Audio upload failed: ${error.message}`);return}const u=supabase.storage.from('audio').getPublicUrl(path).data.publicUrl;update('audio_url',u);setPreview(u)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);const payload={...form};delete payload.id;delete payload.created_at;delete payload.updated_at;if(kind==='gallery')payload.image_fit=payload.image_fit==='contain'?'contain':'cover';if(kind==='audio'&&!payload.audio_url){setSaving(false);alert('Please upload an audio file or enter an Audio URL.');return}if(kind==='live'){payload.id=1;payload.updated_at=new Date().toISOString()}const q=editing?supabase.from(table).update(payload).eq('id',editing.id):kind==='live'?supabase.from(table).upsert(payload):supabase.from(table).insert(payload);const {error}=await q;setSaving(false);if(error){alert(error.message);return}reset();await load()}
 const remove=async(id:any)=>{if(!confirm(`Delete this ${title.toLowerCase()} item?`))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error){alert(error.message);return}await load()}
 const field=(label:string,key:string,placeholder='')=><div className="admin-field"><label>{label}</label><input className={input} value={form[key]??''} onChange={e=>update(key,e.target.value)} placeholder={placeholder}/></div>
 const galleryPreview=preview||form.image_url
 return <div><div className="admin-heading-row"><div className="admin-heading"><h1>{title}</h1><p>Full add, edit and delete controls. Changes are saved directly to Hilltop content.</p></div></div><div className="admin-grid"><section className="admin-panel"><div className="admin-panel-head"><div><h2>{editing?'Edit item':'Add new item'}</h2><span>{editing?'Update and save changes':'Create content'}</span></div>{editing&&<button type="button" className="admin-btn" onClick={reset}>Cancel</button>}</div><div className="admin-panel-body"><form onSubmit={save}>
 {kind==='gallery'&&<>{field('Title','title','Gallery title')}{field('Image URL','image_url','https://…')}<div className="admin-field"><label>Upload image from your device</label><input className={input} type="file" accept="image/*" onChange={e=>upload(e,'image_url','gallery')}/></div><div className="admin-field"><label>Image preview mode</label><select className="admin-select" value={form.image_fit||'cover'} onChange={e=>update('image_fit',e.target.value)}><option value="contain">Fit image to preview</option><option value="cover">Fill image to preview</option></select></div></>}
 {kind==='videos'&&<>{field('Title','title','Sermon title')}{field('Speaker','speaker')}{field('Scripture','scripture')}{field('Category','category')}{field('Video URL','video_url','https://…')}{field('Thumbnail URL','thumbnail_url','https://…')}<div className="admin-field"><label>Or upload thumbnail</label><input className={input} type="file" accept="image/*" onChange={e=>upload(e,'thumbnail_url','gallery')}/></div><label className="admin-field"><span>Featured</span><input type="checkbox" checked={!!form.is_featured} onChange={e=>update('is_featured',e.target.checked)}/></label></>}
 {kind==='audio'&&<><div className="admin-field"><label>Audio file from your device</label><input className={input} type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg,.webm" onChange={uploadAudio}/><small style={{display:'block',marginTop:8,opacity:.7}}>MP3, WAV, M4A, AAC, OGG or WebM · Maximum 100 MB</small></div>{field('Title','title','Audio message title')}{field('Speaker','speaker')}{field('Episode','episode')}{field('Duration','duration')}{field('Audio URL','audio_url','Or paste an audio URL')}{form.audio_url&&<div className="admin-field"><label>Audio preview</label><audio controls preload="metadata" src={form.audio_url} style={{width:'100%'}}/></div>}</>}
 {kind==='live'&&<>{field('Broadcast title','title','Live service')}{field('Stream URL','stream_url','https://…')}<label className="admin-field"><span>Broadcast is live</span><input type="checkbox" checked={!!form.is_live} onChange={e=>update('is_live',e.target.checked)}/></label></>}
 {kind==='gallery'&&galleryPreview&&<div className="admin-field"><label>Live Preview</label><div style={{width:'100%',aspectRatio:'16/10',overflow:'hidden',background:'#08080e',borderRadius:14}}><img src={galleryPreview} alt="Gallery preview" style={{width:'100%',height:'100%',display:'block',objectFit:form.image_fit==='contain'?'contain':'cover',objectPosition:'center'}}/></div><small style={{display:'block',marginTop:8,opacity:.7}}>This preview shows exactly how the image will be fitted or filled in the gallery frame.</small></div>}
 {preview&&kind!=='gallery'&&kind!=='audio'&&<div className="admin-field"><label>Live image preview</label><img src={preview} className="admin-preview" alt="Upload preview"/></div>}
 <div className="admin-form-actions"><button className="admin-btn" type="button" onClick={reset}>Clear</button><button className="admin-btn gold" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Add item'}</button></div></form></div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Existing content</h2><span>{items.length} item{items.length===1?'':'s'}</span></div></div><div className="admin-panel-body"><div className="admin-list">{items.map(x=><div className="admin-list-item" key={String(x.id)}>{(x.image_url||x.thumbnail_url)&&<img src={x.image_url||x.thumbnail_url} alt=""/>}<div className="admin-list-main"><b>{x.title||'Live broadcast'}</b><span>{x.speaker||x.category||x.episode||x.stream_url||''}</span></div><div className="admin-actions"><button type="button" className="admin-mini" onClick={()=>edit(x)}>Edit</button><button type="button" className="admin-mini del" onClick={()=>remove(x.id)}>Delete</button></div></div>)}{!items.length&&<div className="admin-empty">No content yet.</div>}</div></div></section></div></div>
}