import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from '../supabase';
import { GalleryMomentsManager } from '../components/GalleryMomentsManager';

interface AdminPortalProps { onBack: () => void }
interface Minister { id:number|string; name:string; role:string; desc?:string; desc_text?:string; image_url?:string; img?:string; display_order:number }
interface GalleryItem { id:string|number; title:string; image_url:string; created_at?:string; group_id?:string|null; display_order?:number|null }
interface Sermon { id:string; title:string; speaker:string; scripture:string; category:string; video_url:string; thumbnail_url:string; is_featured:boolean; created_at:string }
interface AudioSermon { id:string; title:string; speaker:string; episode:string; duration:string; audio_url:string; created_at?:string }
type Tab = 'overview'|'ministers'|'gallery'|'videos'|'live'|'audio';

const nav: {id:Tab; label:string; short:string}[] = [
  { id:'overview', label:'Overview', short:'OV' },
  { id:'ministers', label:'Ministers', short:'MI' },
  { id:'gallery', label:'Gallery Moments', short:'GA' },
  { id:'videos', label:'Video Sermons', short:'VI' },
  { id:'live', label:'Live Broadcast', short:'LI' },
  { id:'audio', label:'Audio Messages', short:'AU' },
];

const svg = (d:string) => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={d}/></svg>;
const icons: Record<string, React.ReactNode> = {
  overview: svg('M4 13h6V4H4v9Zm0 7h6v-4H4v4Zm10 0h6v-9h-6v9Zm0-16v4h6V4h-6Z'),
  ministers: svg('M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m8-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm6-3a4 4 0 0 1 0 8m4 5v-2a4 4 0 0 0-3-3.87'),
  gallery: svg('m3 17 5-5 4 4 3-3 6 6M5 21h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2-2Zm4-10a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z'),
  videos: svg('m15 10 4.55-2.28A1 1 0 0 1 21 8.62v6.76a1 1 0 0 1-1.45.9L15 14M5 18h8a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2Z'),
  live: svg('M8.5 16.5a5 5 0 0 1 0-9m7 0a5 5 0 0 1 0 9M5 19.5a9 9 0 0 1 0-15m14 0a9 9 0 0 1 0 15M12 12h.01'),
  audio: svg('M12 3a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3Zm-7 9a7 7 0 0 0 14 0M12 19v3m-4 0h8'),
};

const styles = `
.admin-shell{--gold:#d9ad4c;--gold-bright:#f0ca70;--ink:#090a08;--panel:#0f100d;--panel2:#141510;--line:rgba(217,173,76,.18);--muted:#7f806f;min-height:100vh;background:#080906;color:#f4f0e6;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.admin-shell *{box-sizing:border-box}.admin-shell button,.admin-shell input,.admin-shell textarea,.admin-shell select{font:inherit}.admin-shell button{cursor:pointer}
.admin-sidebar{position:fixed;z-index:30;inset:0 auto 0 0;width:252px;background:#0a0b09;border-right:1px solid var(--line);display:flex;flex-direction:column;transition:.22s ease}
.admin-brand{height:88px;padding:20px 24px;border-bottom:1px solid rgba(255,255,255,.055);display:flex;align-items:center;gap:12px}.admin-mark{width:40px;height:40px;border:1px solid rgba(217,173,76,.55);display:grid;place-items:center;color:var(--gold);font-family:Georgia,serif;font-size:17px}.admin-brand strong{display:block;font:600 14px Georgia,serif;letter-spacing:.02em}.admin-brand span{display:block;color:#68695d;font-size:9px;letter-spacing:.18em;text-transform:uppercase;margin-top:3px}
.admin-nav{padding:24px 12px}.admin-nav-label{padding:0 12px 10px;color:#53544c;font-size:9px;letter-spacing:.2em;text-transform:uppercase}.admin-nav button{width:100%;display:flex;align-items:center;gap:12px;border:1px solid transparent;background:transparent;color:#929387;padding:11px 12px;margin:2px 0;text-align:left;font-size:12px;transition:.16s}.admin-nav button:hover{color:#eee8dc;background:#11120f}.admin-nav button.active{color:#f2cd73;background:#171811;border-color:rgba(217,173,76,.17);box-shadow:inset 2px 0 var(--gold)}.admin-nav-icon{width:18px;height:18px;display:grid;place-items:center;color:inherit}.admin-nav-icon svg{width:17px;height:17px}.admin-sidebar-bottom{margin-top:auto;padding:18px 16px;border-top:1px solid rgba(255,255,255,.05)}
.admin-main{margin-left:252px;min-height:100vh}.admin-topbar{height:88px;border-bottom:1px solid rgba(255,255,255,.06);display:flex;align-items:center;justify-content:space-between;padding:0 34px;background:rgba(8,9,6,.92);position:sticky;top:0;z-index:20;backdrop-filter:blur(12px)}.admin-kicker{font-size:9px;letter-spacing:.2em;text-transform:uppercase;color:var(--gold);margin-bottom:6px}.admin-top-title{font:500 21px Georgia,serif;color:#f5f0e5}.admin-top-actions{display:flex;align-items:center;gap:10px}.admin-btn{height:38px;padding:0 15px;border:1px solid rgba(217,173,76,.24);background:#12130f;color:#ded9cd;font-size:10px;letter-spacing:.11em;text-transform:uppercase}.admin-btn:hover{border-color:rgba(217,173,76,.55);color:#f5d47d}.admin-btn.gold{background:linear-gradient(135deg,#f0ca70,#c9922e);border-color:#e0b45b;color:#17130a;font-weight:700}.admin-btn.danger{border-color:rgba(220,70,70,.25);color:#d98888}.admin-user{height:38px;display:flex;align-items:center;gap:9px;padding:0 11px;border-left:1px solid rgba(255,255,255,.08);margin-left:5px}.admin-avatar{width:28px;height:28px;border-radius:50%;background:#1b1c16;border:1px solid rgba(217,173,76,.35);display:grid;place-items:center;color:var(--gold);font-size:10px}.admin-user small{display:block;color:#5f6058;font-size:8px;letter-spacing:.12em;text-transform:uppercase}.admin-user b{display:block;color:#d8d3c7;font-size:10px;font-weight:500;margin-top:1px}
.admin-content{padding:30px 34px 50px;max-width:1500px}.admin-heading-row{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:24px}.admin-heading h1{font:500 34px Georgia,serif;margin:0;color:#f7f1e5}.admin-heading p{margin:7px 0 0;color:#707169;font-size:12px}.admin-date{color:#64665b;font-size:9px;letter-spacing:.12em;text-transform:uppercase}
.admin-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border:1px solid rgba(255,255,255,.07);background:#0c0d0a;margin-bottom:28px}.admin-stat{min-height:108px;padding:17px 18px;border-right:1px solid rgba(255,255,255,.06);position:relative}.admin-stat:last-child{border-right:0}.admin-stat-label{color:#696b60;font-size:8px;letter-spacing:.18em;text-transform:uppercase;display:flex;align-items:center;gap:7px}.admin-stat-value{font:500 27px Georgia,serif;margin-top:15px;color:#f0eadf}.admin-stat.gold .admin-stat-value{color:var(--gold-bright)}.admin-dot{width:6px;height:6px;background:var(--gold);display:inline-block}.admin-dot.red{background:#d94e4e}.admin-dot.green{background:#45b97a}
.admin-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.75fr);gap:18px}.admin-panel{background:#0d0e0b;border:1px solid rgba(255,255,255,.07)}.admin-panel-head{min-height:62px;padding:16px 18px;border-bottom:1px solid rgba(255,255,255,.06);display:flex;align-items:center;justify-content:space-between}.admin-panel-head h2{margin:0;font:500 16px Georgia,serif}.admin-panel-head span{color:#65675e;font-size:9px;letter-spacing:.13em;text-transform:uppercase}.admin-panel-body{padding:18px}.admin-table{width:100%;border-collapse:collapse}.admin-table th{color:#5f6158;text-align:left;font-size:8px;letter-spacing:.15em;text-transform:uppercase;font-weight:500;padding:10px 12px;border-bottom:1px solid rgba(255,255,255,.08)}.admin-table td{padding:13px 12px;border-bottom:1px solid rgba(255,255,255,.055);font-size:11px;color:#c8c4b9}.admin-table tr:last-child td{border-bottom:0}.admin-table tr:hover td{background:rgba(255,255,255,.018)}.admin-name{color:#eee9de;font-weight:600}.admin-sub{display:block;color:#66685f;font-size:9px;margin-top:4px}.admin-tag{display:inline-flex;align-items:center;padding:4px 7px;background:#171811;border:1px solid rgba(217,173,76,.14);color:#cfa34b;font-size:8px;letter-spacing:.08em;text-transform:uppercase}.admin-status{display:inline-flex;align-items:center;gap:6px;color:#75c69c;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.admin-actions{display:flex;gap:7px}.admin-mini{border:1px solid rgba(255,255,255,.09);background:#11120f;color:#aaa99e;font-size:9px;padding:7px 9px;text-transform:uppercase;letter-spacing:.08em}.admin-mini:hover{color:#eee;border-color:rgba(217,173,76,.3)}.admin-mini.del{color:#d78585;border-color:rgba(220,70,70,.18)}
.admin-quick{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.admin-quick button{min-height:84px;background:#11120f;border:1px solid rgba(255,255,255,.06);color:#c8c4b8;text-align:left;padding:14px}.admin-quick button:hover{border-color:rgba(217,173,76,.3);background:#151610}.admin-quick b{display:block;font-size:11px;margin:7px 0 4px;color:#eee8dc}.admin-quick span{font-size:8px;color:#65675e;line-height:1.4}.admin-quick-icon{color:var(--gold);width:17px;height:17px}.admin-quick-icon svg{width:17px;height:17px}
.admin-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.admin-field{margin-bottom:14px}.admin-field label{display:block;color:#6b6d63;font-size:8px;letter-spacing:.16em;text-transform:uppercase;margin-bottom:7px}.admin-input,.admin-select,.admin-textarea{width:100%;background:#11120f;border:1px solid rgba(255,255,255,.09);color:#eee9de;outline:none;padding:10px 11px;font-size:11px;border-radius:0}.admin-input,.admin-select{height:40px}.admin-textarea{min-height:120px;resize:vertical;line-height:1.6}.admin-input:focus,.admin-select:focus,.admin-textarea:focus{border-color:rgba(217,173,76,.55);box-shadow:0 0 0 2px rgba(217,173,76,.05)}.admin-form-actions{display:flex;gap:8px;justify-content:flex-end;border-top:1px solid rgba(255,255,255,.06);padding-top:16px;margin-top:4px}.admin-helper{color:#5f6159;font-size:9px;line-height:1.5}.admin-preview{width:100%;height:180px;object-fit:cover;background:#111;border:1px solid rgba(255,255,255,.07);margin-top:8px}.admin-slotbar{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:16px}.admin-slotbar button{min-width:38px;height:32px;background:#11120f;border:1px solid rgba(255,255,255,.08);color:#777970;font-size:9px}.admin-slotbar button.active{background:#1b1910;border-color:rgba(217,173,76,.55);color:#f0c86b}.admin-list{display:grid;gap:9px}.admin-list-item{display:flex;align-items:center;gap:12px;padding:11px;background:#10110e;border:1px solid rgba(255,255,255,.055)}.admin-list-item img{width:50px;height:50px;object-fit:cover}.admin-list-main{min-width:0;flex:1}.admin-list-main b{display:block;font-size:11px;color:#e5e0d5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.admin-list-main span{display:block;color:#686a61;font-size:9px;margin-top:4px}.admin-empty{padding:30px;text-align:center;color:#5d5f56;font-size:10px;border:1px dashed rgba(255,255,255,.08)}
.admin-live-card{border:1px solid rgba(217,173,76,.22);background:linear-gradient(135deg,#14150f,#0d0e0b);padding:22px;position:relative;overflow:hidden}.admin-live-card:after{content:"";position:absolute;width:260px;height:260px;border-radius:50%;right:-110px;top:-130px;background:rgba(217,173,76,.06)}.admin-live-status{display:inline-flex;align-items:center;gap:7px;color:#e8bd63;font-size:9px;letter-spacing:.14em;text-transform:uppercase}.admin-pulse{width:7px;height:7px;border-radius:50%;background:#45c483;box-shadow:0 0 0 5px rgba(69,196,131,.08)}.admin-live-card h3{font:500 23px Georgia,serif;margin:14px 0 6px}.admin-live-card p{font-size:10px;color:#777970;margin:0 0 18px}.admin-switch{display:inline-flex;align-items:center;gap:8px;cursor:pointer;color:#a9aa9f;font-size:9px;text-transform:uppercase;letter-spacing:.1em}.admin-switch input{display:none}.admin-switch i{width:34px;height:18px;border-radius:20px;background:#292b24;border:1px solid #45473b;position:relative}.admin-switch i:after{content:"";position:absolute;width:12px;height:12px;top:2px;left:2px;border-radius:50%;background:#777970;transition:.18s}.admin-switch input:checked+i{background:#5e4720;border-color:#b48632}.admin-switch input:checked+i:after{left:18px;background:#f3c86a}
.admin-login{min-height:100vh;background:#080906;display:grid;place-items:center;padding:24px;position:relative;overflow:hidden}.admin-login:before{content:"";position:absolute;width:650px;height:650px;border-radius:50%;background:radial-gradient(circle,rgba(217,173,76,.08),transparent 65%);top:50%;left:50%;transform:translate(-50%,-50%)}.admin-login-card{position:relative;width:min(430px,100%);background:#0d0e0b;border:1px solid rgba(217,173,76,.22);padding:34px;box-shadow:0 30px 80px rgba(0,0,0,.45)}.admin-login-brand{display:flex;align-items:center;gap:12px;margin-bottom:30px}.admin-login-card h1{font:500 27px Georgia,serif;margin:0}.admin-login-card .admin-kicker{margin-bottom:8px}.admin-error{padding:11px;border:1px solid rgba(220,70,70,.2);background:rgba(220,70,70,.05);color:#db9999;font-size:10px;margin-bottom:16px}.admin-login-note{text-align:center;color:#4f5149;font-size:8px;letter-spacing:.1em;text-transform:uppercase;margin-top:22px}
@media(max-width:1050px){.admin-sidebar{width:220px}.admin-main{margin-left:220px}.admin-content{padding:26px 22px}.admin-stats{grid-template-columns:repeat(3,1fr)}.admin-stat:nth-child(3){border-right:0}.admin-stat:nth-child(n+4){border-top:1px solid rgba(255,255,255,.06)}.admin-grid{grid-template-columns:1fr}}
@media(max-width:760px){.admin-sidebar{position:static;width:100%;height:auto}.admin-shell{display:block}.admin-brand{height:70px}.admin-nav{display:flex;overflow:auto;padding:8px}.admin-nav-label,.admin-sidebar-bottom{display:none}.admin-nav button{min-width:max-content;width:auto;padding:9px 11px}.admin-nav button.active{box-shadow:inset 0 -2px var(--gold)}.admin-main{margin-left:0}.admin-topbar{height:auto;min-height:72px;padding:12px 16px}.admin-top-actions .admin-btn:not(.gold){display:none}.admin-user{display:none}.admin-content{padding:22px 14px 40px}.admin-heading-row{align-items:flex-start;gap:12px}.admin-heading h1{font-size:28px}.admin-date{display:none}.admin-stats{grid-template-columns:repeat(2,1fr)}.admin-stat{border-right:0}.admin-stat:nth-child(odd){border-right:1px solid rgba(255,255,255,.06)}.admin-stat:nth-child(n+3){border-top:1px solid rgba(255,255,255,.06)}.admin-form-grid{grid-template-columns:1fr}.admin-panel-body{padding:13px}.admin-table{min-width:680px}.admin-panel.table-wrap{overflow:auto}.admin-quick{grid-template-columns:1fr 1fr}.admin-login-card{padding:26px}}
@media(max-width:430px){.admin-quick{grid-template-columns:1fr}.admin-top-title{font-size:18px}.admin-stats{grid-template-columns:1fr 1fr}.admin-stat{min-height:94px;padding:14px}.admin-stat-value{font-size:23px;margin-top:11px}}
`;

export function AdminPortal({ onBack }: AdminPortalProps) {
  const [loading,setLoading]=useState(true),[isAdmin,setIsAdmin]=useState(false),[authError,setAuthError]=useState('');
  const [tab,setTab]=useState<Tab>('overview'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[deploying,setDeploying]=useState(false);
  const [ministers,setMinisters]=useState<Minister[]>([]),[selectedMinister,setSelectedMinister]=useState(1),[mName,setMName]=useState(''),[mRole,setMRole]=useState(''),[mDesc,setMDesc]=useState(''),[mImage,setMImage]=useState('');
  const [gallery,setGallery]=useState<GalleryItem[]>([]);
  const [sermons,setSermons]=useState<Sermon[]>([]),[vTitle,setVTitle]=useState(''),[vSpeaker,setVSpeaker]=useState(''),[vScripture,setVScripture]=useState(''),[vCategory,setVCategory]=useState('Faith'),[vUrl,setVUrl]=useState(''),[vThumb,setVThumb]=useState(''),[vFeatured,setVFeatured]=useState(false);
  const [liveTitle,setLiveTitle]=useState(''),[liveUrl,setLiveUrl]=useState(''),[liveActive,setLiveActive]=useState(false);
  const [audio,setAudio]=useState<AudioSermon[]>([]),[aTitle,setATitle]=useState(''),[aSpeaker,setASpeaker]=useState(''),[aEpisode,setAEpisode]=useState('Ep. 1'),[aDuration,setADuration]=useState(''),[aUrl,setAUrl]=useState('');

  const fetchMinisters=async()=>{const {data}=await supabase.from('ministers').select('*').order('display_order',{ascending:true});if(data){setMinisters(data);const m=data.find(x=>(x.display_order??x.id)===selectedMinister);if(m){setMName(m.name||'');setMRole(m.role||'');setMDesc(m.desc_text||m.desc||'');setMImage(m.image_url||m.img||'')}}};
  const fetchGallery=async()=>{const {data}=await supabase.from('gallery_moments').select('*').order('created_at',{ascending:false});if(data)setGallery(data)};
  const fetchSermons=async()=>{const {data}=await supabase.from('sermons').select('*').order('created_at',{ascending:false});if(data)setSermons(data)};
  const fetchLive=async()=>{const {data}=await supabase.from('live_stream').select('*').eq('id',1).maybeSingle();if(data){setLiveTitle(data.title||'');setLiveUrl(data.stream_url||'');setLiveActive(!!data.is_live)}};
  const fetchAudio=async()=>{const {data}=await supabase.from('audio_sermons').select('*').order('created_at',{ascending:false});if(data)setAudio(data)};
  const refresh=async()=>{await Promise.all([fetchMinisters(),fetchGallery(),fetchSermons(),fetchLive(),fetchAudio()])};

  useEffect(()=>{(async()=>{try{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(user.email==='taiwiboluwa@gmail.com'||profile?.role==='admin'||user.user_metadata?.role==='admin'){setIsAdmin(true);await refresh()}else setAuthError('Access denied: this account is not assigned as an admin.')}catch(e:any){setAuthError(e.message||'Authentication error')}finally{setLoading(false)}})()},[]);
  const login=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setAuthError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setAuthError(error.message);setLoading(false);return}const {data:{user}}=await supabase.auth.getUser();const {data:profile}=await supabase.from('profiles').select('role').eq('id',user?.id).maybeSingle();if(user&&(user.email==='taiwiboluwa@gmail.com'||profile?.role==='admin'||user.user_metadata?.role==='admin')){setIsAdmin(true);await refresh()}else setAuthError('Access denied: this account is not assigned as an admin.');setLoading(false)};
  const logout=async()=>{await supabase.auth.signOut();setIsAdmin(false)};
  const upload=async(e:React.ChangeEvent<HTMLInputElement>,bucket:string,setter:(url:string)=>void)=>{const file=e.target.files?.[0];if(!file)return;const ext=file.name.split('.').pop();const path=`${Date.now()}_${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:true});if(error){alert(error.message);return}setter(supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl)};
  const chooseMinister=(order:number)=>{setSelectedMinister(order);const m=ministers.find(x=>(x.display_order??x.id)===order);setMName(m?.name||'');setMRole(m?.role||'');setMDesc(m?.desc_text||m?.desc||'');setMImage(m?.image_url||m?.img||'')};
  const saveMinister=async(e:React.FormEvent)=>{e.preventDefault();if(!mName.trim()||!mRole.trim()){alert('Enter the minister name and role.');return}const existing=ministers.find(x=>(x.display_order??x.id)===selectedMinister);const payload={name:mName.trim(),role:mRole.trim(),desc:mDesc,desc_text:mDesc,image_url:mImage,img:mImage,display_order:selectedMinister};const result=existing?await supabase.from('ministers').update(payload).eq('id',existing.id):await supabase.from('ministers').insert(payload);if(result.error)alert(result.error.message);else{await fetchMinisters();alert(`Minister slot ${selectedMinister} saved.`)}};
  const removeMinister=async()=>{const m=ministers.find(x=>(x.display_order??x.id)===selectedMinister);if(!m)return;if(!confirm(`Remove ${m.name} from Minister Slot ${selectedMinister}?`))return;const {error}=await supabase.from('ministers').delete().eq('id',m.id);if(error)alert(error.message);else{setMName('');setMRole('');setMDesc('');setMImage('');await fetchMinisters()}};
  const addSermon=async(e:React.FormEvent)=>{e.preventDefault();if(!vTitle.trim()||!vUrl.trim()){alert('Add a sermon title and video URL.');return}const {error}=await supabase.from('sermons').insert({title:vTitle.trim(),speaker:vSpeaker,scripture:vScripture,category:vCategory,video_url:vUrl,thumbnail_url:vThumb,is_featured:vFeatured});if(error)alert(error.message);else{setVTitle('');setVSpeaker('');setVScripture('');setVUrl('');setVThumb('');setVFeatured(false);await fetchSermons()}};
  const removeSermon=async(id:string)=>{if(!confirm('Delete this video sermon?'))return;const {error}=await supabase.from('sermons').delete().eq('id',id);if(error)alert(error.message);else fetchSermons()};
  const saveLive=async(e:React.FormEvent)=>{e.preventDefault();const {error}=await supabase.from('live_stream').upsert({id:1,title:liveTitle,stream_url:liveUrl,is_live:liveActive,updated_at:new Date().toISOString()});if(error)alert(error.message);else alert('Live broadcast updated.')};
  const removeLive=async()=>{if(!confirm('Remove the current live broadcast and take it offline?'))return;const {error}=await supabase.from('live_stream').upsert({id:1,title:'',stream_url:'',is_live:false,updated_at:new Date().toISOString()});if(error)alert(error.message);else{setLiveTitle('');setLiveUrl('');setLiveActive(false)}};
  const addAudio=async(e:React.FormEvent)=>{e.preventDefault();if(!aTitle.trim()||!aUrl.trim()){alert('Add an audio title and audio URL.');return}const {error}=await supabase.from('audio_sermons').insert({title:aTitle.trim(),speaker:aSpeaker,episode:aEpisode,duration:aDuration,audio_url:aUrl});if(error)alert(error.message);else{setATitle('');setASpeaker('');setAUrl('');await fetchAudio()}};
  const removeAudio=async(id:string)=>{if(!confirm('Delete this audio message?'))return;const {error}=await supabase.from('audio_sermons').delete().eq('id',id);if(error)alert(error.message);else fetchAudio()};
  const deploy=async()=>{setDeploying(true);try{const r=await fetch('https://api.vercel.com/v1/integrations/deploy/prj_Yij9Z5IGRxiUBFNiVJbzBAqpqqA2/L9JSap9y4V',{method:'POST'});alert(r.ok?'Deployment triggered successfully!':'Failed to trigger deployment.')}catch(e:any){alert(e.message)}finally{setDeploying(false)}};
  const counts=useMemo(()=>({ministers:ministers.length,gallery:gallery.length,videos:sermons.length,live:liveActive?1:0,audio:audio.length}),[ministers,gallery,sermons,liveActive,audio]);
  const active=nav.find(x=>x.id===tab) || nav[0];
  const today=new Intl.DateTimeFormat('en-NG',{weekday:'long',day:'2-digit',month:'short',year:'numeric'}).format(new Date());

  if(loading)return <><style>{styles}</style><div className="admin-login"><div className="admin-login-card"><div className="admin-login-brand"><div className="admin-mark">H</div><div><div className="admin-kicker">Hilltop Ministry</div><h1>Authenticating</h1></div></div><div className="admin-helper">Checking your secure administrator session…</div></div></div></>;
  if(!isAdmin)return <><style>{styles}</style><div className="admin-login"><div className="admin-login-card"><div className="admin-login-brand"><div className="admin-mark">H</div><div><div className="admin-kicker">Hilltop Prayer & Evangelical Ministry</div><h1>Admin Access</h1></div></div>{authError&&<div className="admin-error">{authError}</div>}<form onSubmit={login}><div className="admin-field"><label>Email address</label><input className="admin-input" value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="admin@hilltopministries.org"/></div><div className="admin-field"><label>Password</label><input className="admin-input" value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="Enter your password"/></div><button className="admin-btn gold" style={{width:'100%',height:44}} type="submit">Sign in to dashboard</button></form><button className="admin-btn" style={{width:'100%',marginTop:9}} onClick={onBack}>← Return to website</button><div className="admin-login-note">Restricted administrator area · Hilltop Ministries</div></div></div></>;

  const Stat=({label,value,kind=''}:{label:string;value:number|string;kind?:string})=><div className={`admin-stat ${kind}`}><div className="admin-stat-label"><span className={`admin-dot ${kind==='red'?'red':kind==='green'?'green':''}`}/>{label}</div><div className="admin-stat-value">{value}</div></div>;
  const SectionTitle=({title,sub,action}:{title:string;sub?:string;action?:React.ReactNode})=><div className="admin-panel-head"><div><h2>{title}</h2>{sub&&<span>{sub}</span>}</div>{action}</div>;

  const renderOverview=()=> <><div className="admin-heading-row"><div className="admin-heading"><h1>Dashboard</h1><p>A clean command centre for Hilltop Ministries content.</p></div><div className="admin-date">{today}</div></div><div className="admin-stats"><Stat label="Ministers" value={counts.ministers}/><Stat label="Gallery Moments" value={counts.gallery}/><Stat label="Video Sermons" value={counts.videos}/><Stat label="Audio Messages" value={counts.audio}/><Stat label="Live Broadcast" value={counts.live} kind={counts.live?'green':'red'}/></div><div className="admin-grid"><section className="admin-panel table-wrap"><SectionTitle title="Recent video sermons" sub={`${counts.videos} published items`} action={<button className="admin-btn" onClick={()=>setTab('videos')}>Manage all</button>}/><div className="admin-panel-body">{sermons.length?<table className="admin-table"><thead><tr><th>Title</th><th>Category</th><th>Speaker</th><th>Status</th></tr></thead><tbody>{sermons.slice(0,5).map(s=><tr key={s.id}><td><div className="admin-name">{s.title}</div><span className="admin-sub">{s.scripture||'No scripture added'}</span></td><td><span className="admin-tag">{s.category||'Faith'}</span></td><td>{s.speaker||'—'}</td><td><span className="admin-status"><i className="admin-dot green"/> Published</span></td></tr>)}</tbody></table>:<div className="admin-empty">No video sermons have been added yet.</div>}</div></section><div style={{display:'grid',gap:18}}><section className="admin-panel"><SectionTitle title="Quick actions" sub="Jump into content"/><div className="admin-panel-body"><div className="admin-quick">{[['ministers','Ministers','Update ministry team'],['gallery','Gallery','Add a new moment'],['videos','Video sermons','Publish a message'],['live','Live broadcast','Update stream status']].map(([id,title,desc])=><button key={id} onClick={()=>setTab(id as Tab)}><div className="admin-quick-icon">{icons[id]}</div><b>{title}</b><span>{desc}</span></button>)}</div></div></section><section className="admin-live-card"><div className="admin-live-status"><i className="admin-pulse"/> {liveActive?'Live now':'Broadcast offline'}</div><h3>{liveTitle||'No live broadcast configured'}</h3><p>{liveActive?'Your public site is currently showing the live broadcast.':'Set a title and stream URL when you are ready to go live.'}</p><button className="admin-btn" onClick={()=>setTab('live')}>{liveActive?'Manage live stream':'Configure broadcast'} →</button></section></div></div></>;

  const renderMinisters=()=> <><div className="admin-heading-row"><div className="admin-heading"><h1>Ministers</h1><p>Manage the people and roles shown across the ministry website.</p></div></div><div className="admin-grid"><section className="admin-panel"><SectionTitle title="Minister editor" sub={`Slot ${selectedMinister} of 5`}/><div className="admin-panel-body"><div className="admin-slotbar">{[1,2,3,4,5].map(n=><button key={n} className={selectedMinister===n?'active':''} onClick={()=>chooseMinister(n)}>Slot {n}</button>)}</div><form onSubmit={saveMinister}><div className="admin-form-grid"><div><div className="admin-field"><label>Name</label><input className="admin-input" value={mName} onChange={e=>setMName(e.target.value)} placeholder="Minister name"/></div><div className="admin-field"><label>Role</label><input className="admin-input" value={mRole} onChange={e=>setMRole(e.target.value)} placeholder="Resident Pastor"/></div><div className="admin-field"><label>Photo URL</label><input className="admin-input" value={mImage} onChange={e=>setMImage(e.target.value)} placeholder="https://…"/></div><div className="admin-field"><label>Or upload a photo</label><input className="admin-input" type="file" accept="image/*" onChange={e=>upload(e,'minister-images',setMImage)}/></div></div><div><div className="admin-field"><label>Biography</label><textarea className="admin-textarea" style={{minHeight:210}} value={mDesc} onChange={e=>setMDesc(e.target.value)} placeholder="Write a short biography…"/></div>{mImage&&<img className="admin-preview" src={mImage} alt="Minister preview"/>}</div></div><div className="admin-form-actions"><button type="button" className="admin-btn danger" onClick={removeMinister}>Remove slot</button><button className="admin-btn gold" type="submit">Save minister</button></div></form></div></section><section className="admin-panel"><SectionTitle title="Current team" sub={`${counts.ministers} active records`}/><div className="admin-panel-body"><div className="admin-list">{ministers.length?ministers.map(m=><button className="admin-list-item" key={String(m.id)} onClick={()=>chooseMinister(m.display_order)} style={{textAlign:'left'}}><img src={m.image_url||m.img||''} alt=""/><div className="admin-list-main"><b>{m.name}</b><span>{m.role}</span></div><span className="admin-tag">Slot {m.display_order}</span></button>):<div className="admin-empty">No minister records found.</div>}</div></div></section></div></>;

  const renderGallery=()=> <><div className="admin-heading-row"><div className="admin-heading"><h1>Gallery Moments</h1><p>Upload multiple pictures together as one gallery group.</p></div></div><GalleryMomentsManager /></>;

  const renderVideos=()=> <><div className="admin-heading-row"><div className="admin-heading"><h1>Video Sermons</h1><p>Publish teachings, sermons and video messages.</p></div></div><div className="admin-grid"><section className="admin-panel"><SectionTitle title="Publish sermon" sub="New video content"/><div className="admin-panel-body"><form onSubmit={addSermon}><div className="admin-form-grid"><div><div className="admin-field"><label>Title</label><input className="admin-input" value={vTitle} onChange={e=>setVTitle(e.target.value)} placeholder="The Power of Persistent Prayer"/></div><div className="admin-field"><label>Speaker</label><input className="admin-input" value={vSpeaker} onChange={e=>setVSpeaker(e.target.value)} placeholder="Pastor Emmanuel Adeyemi"/></div><div className="admin-field"><label>Scripture</label><input className="admin-input" value={vScripture} onChange={e=>setVScripture(e.target.value)} placeholder="Luke 18:1-8"/></div><div className="admin-field"><label>Category</label><select className="admin-select" value={vCategory} onChange={e=>setVCategory(e.target.value)}>{['Faith','Prayer','Healing','Deliverance','Evangelism'].map(x=><option key={x}>{x}</option>)}</select></div></div><div><div className="admin-field"><label>Video URL</label><input className="admin-input" value={vUrl} onChange={e=>setVUrl(e.target.value)} placeholder="YouTube or video URL"/></div><div className="admin-field"><label>Thumbnail URL</label><input className="admin-input" value={vThumb} onChange={e=>setVThumb(e.target.value)} placeholder="https://…"/></div><label className="admin-switch"><input type="checkbox" checked={vFeatured} onChange={e=>setVFeatured(e.target.checked)}/><i/> Featured sermon</label>{vThumb&&<img className="admin-preview" src={vThumb} alt="Thumbnail preview"/>}</div></div><div className="admin-form-actions"><button className="admin-btn gold" type="submit">Publish video</button></div></form></div></section><section className="admin-panel table-wrap"><SectionTitle title="Published sermons" sub={`${counts.videos} videos`}/><div className="admin-panel-body">{sermons.length?<table className="admin-table"><thead><tr><th>Title</th><th>Category</th><th>Action</th></tr></thead><tbody>{sermons.map(s=><tr key={s.id}><td><div className="admin-name">{s.title}</div><span className="admin-sub">{s.speaker||'No speaker'} · {s.scripture||'No scripture'}</span></td><td><span className="admin-tag">{s.category||'Faith'}</span></td><td><button className="admin-mini del" onClick={()=>removeSermon(s.id)}>Delete</button></td></tr>)}</tbody></table>:<div className="admin-empty">No video sermons yet.</div>}</div></section></div></>;

  const renderLive=()=> <><div className="admin-heading-row"><div className="admin-heading"><h1>Live Broadcast</h1><p>Control the live stream status shown on the public website.</p></div></div><div className="admin-grid"><section className="admin-panel"><SectionTitle title="Broadcast settings" sub="One live broadcast at a time"/><div className="admin-panel-body"><form onSubmit={saveLive}><div className="admin-field"><label>Broadcast title</label><input className="admin-input" value={liveTitle} onChange={e=>setLiveTitle(e.target.value)} placeholder="Sunday Service — Live"/></div><div className="admin-field"><label>Stream URL</label><input className="admin-input" value={liveUrl} onChange={e=>setLiveUrl(e.target.value)} placeholder="https://youtube.com/live/…"/></div><label className="admin-switch"><input type="checkbox" checked={liveActive} onChange={e=>setLiveActive(e.target.checked)}/><i/> Broadcast is live</label><div className="admin-form-actions"><button type="button" className="admin-btn danger" onClick={removeLive}>Take offline</button><button className="admin-btn gold" type="submit">Save broadcast</button></div></form></div></section><section className="admin-live-card"><div className="admin-live-status"><i className="admin-pulse"/> {liveActive?'LIVE':'OFFLINE'}</div><h3>{liveTitle||'No title set'}</h3><p>{liveUrl||'Add your YouTube, Facebook or stream destination URL.'}</p>{liveActive&&<button className="admin-btn gold" onClick={()=>window.open(liveUrl,'_blank','noopener,noreferrer')}>Open stream ↗</button>}</section></div></>;

  const renderAudio=()=> <><div className="admin-heading-row"><div className="admin-heading"><h1>Audio Messages</h1><p>Publish audio sermons and messages for listeners.</p></div></div><div className="admin-grid"><section className="admin-panel"><SectionTitle title="Add audio message" sub="New audio content"/><div className="admin-panel-body"><form onSubmit={addAudio}><div className="admin-form-grid"><div><div className="admin-field"><label>Title</label><input className="admin-input" value={aTitle} onChange={e=>setATitle(e.target.value)} placeholder="Morning Prayer"/></div><div className="admin-field"><label>Speaker</label><input className="admin-input" value={aSpeaker} onChange={e=>setASpeaker(e.target.value)} placeholder="Pastor Emmanuel Adeyemi"/></div></div><div><div className="admin-field"><label>Episode</label><input className="admin-input" value={aEpisode} onChange={e=>setAEpisode(e.target.value)} placeholder="Ep. 1"/></div><div className="admin-field"><label>Duration</label><input className="admin-input" value={aDuration} onChange={e=>setADuration(e.target.value)} placeholder="32 min"/></div></div></div><div className="admin-field"><label>Audio URL</label><input className="admin-input" value={aUrl} onChange={e=>setAUrl(e.target.value)} placeholder="https://…"/></div><div className="admin-form-actions"><button className="admin-btn gold" type="submit">Publish audio</button></div></form></div></section><section className="admin-panel"><SectionTitle title="Published audio" sub={`${counts.audio} messages`}/><div className="admin-panel-body">{audio.length?<div className="admin-list">{audio.map(a=><div className="admin-list-item" key={a.id}><div className="admin-avatar">♪</div><div className="admin-list-main"><b>{a.title}</b><span>{a.speaker||'No speaker'} · {a.episode||''} {a.duration?`· ${a.duration}`:''}</span></div><button className="admin-mini del" onClick={()=>removeAudio(a.id)}>Delete</button></div>)}</div>:<div className="admin-empty">No audio messages yet.</div>}</div></section></div></>;

  const render=()=>tab==='overview'?renderOverview():tab==='ministers'?renderMinisters():tab==='gallery'?renderGallery():tab==='videos'?renderVideos():tab==='live'?renderLive():renderAudio();

  return <><style>{styles}</style><div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><div className="admin-mark">H</div><div><strong>Hilltop Ministries</strong><span>Admin workspace</span></div></div><nav className="admin-nav"><div className="admin-nav-label">Workspace</div>{nav.map(item=><button key={item.id} className={tab===item.id?'active':''} onClick={()=>setTab(item.id)}><span className="admin-nav-icon">{icons[item.id]}</span>{item.label}</button>)}</nav><div className="admin-sidebar-bottom"><button className="admin-btn" style={{width:'100%'}} onClick={onBack}>View website ↗</button><button className="admin-btn danger" style={{width:'100%',marginTop:8}} onClick={logout}>Sign out</button></div></aside><main className="admin-main"><header className="admin-topbar"><div><div className="admin-kicker">Admin dashboard</div><div className="admin-top-title">{active.label}</div></div><div className="admin-top-actions"><button className="admin-btn" onClick={()=>window.open('https://hilltopministries.org/','_blank','noopener,noreferrer')}>Visit site ↗</button><button className="admin-btn gold" onClick={deploy} disabled={deploying}>{deploying?'Deploying…':'+ Deploy changes'}</button><div className="admin-user"><div className="admin-avatar">TB</div><div><small>Administrator</small><b>Taiwo</b></div></div></div></header><div className="admin-content">{render()}</div></main></div></>;
}
